bzutil = require("__LunarLandings__.bzutil")
data_util = require("__LunarLandings__.data-util")

require "__LunarLandings__.prototypes.custom-input"
require "__LunarLandings__.prototypes.item-groups"
require "__LunarLandings__.prototypes.rocket-silo"
require "__LunarLandings__.prototypes.rocket-parts"
require "__LunarLandings__.prototypes.electric-furnace"
require "__LunarLandings__.prototypes.rtg"
require "__LunarLandings__.prototypes.core-extractor"
require "__LunarLandings__.prototypes.landing-pad"
require "__LunarLandings__.prototypes.tiles"
require "__LunarLandings__.prototypes.moon-rock"
require "__LunarLandings__.prototypes.silicon"
require "__LunarLandings__.prototypes.oxygen"
require "__LunarLandings__.prototypes.fusion-fuel"
require "__LunarLandings__.prototypes.ice"
require "__LunarLandings__.prototypes.low-grav-assembling-machine"
require "__LunarLandings__.prototypes.telescope"
require "__LunarLandings__.prototypes.moon-rails"
require "__LunarLandings__.prototypes.space-science"
require "__LunarLandings__.prototypes.data-cards"
require "__LunarLandings__.prototypes.oxygen-diffuser"
require "__LunarLandings__.prototypes.technology"
require "__LunarLandings__.prototypes.autoplace-controls"
--require "__LunarLandings__.prototypse.remote-character"
require "__LunarLandings__.prototypes.recipe-changes"
--require "__LunarLandings__.prototypes.construction-bots"
