local item_sounds = require("__base__.prototypes.item_sounds")

local function find_item_prototype(name, allow_fail)
  for item_type in pairs(defines.prototypes.item) do
    local item = (data.raw[item_type] or {})[name]
    if item then return item end
  end
  if not allow_fail then
    error("Could not find item " .. name)
  end
end

local function copy_item_sounds(name, from, allow_fail)
  local item = find_item_prototype(name, allow_fail)
  if not item then return end
  local from_item = find_item_prototype(from)
  item.inventory_move_sound = item.inventory_move_sound or table.deepcopy(from_item.inventory_move_sound)
  item.pick_sound = item.pick_sound or table.deepcopy(from_item.pick_sound)
  item.drop_sound = item.drop_sound or table.deepcopy(from_item.drop_sound)
end

copy_item_sounds("ll-interstellar-satellite", "flying-robot-frame", true)
copy_item_sounds("ll-moon-rail", "rail")
copy_item_sounds("ll-lunar-foundation", "concrete")
copy_item_sounds("ll-rtg", "uranium-fuel-cell")
copy_item_sounds("ll-steam-condenser", "boiler")
copy_item_sounds("ll-core-extractor", "burner-mining-drill")
copy_item_sounds("ll-heat-furnace", "steel-furnace")
copy_item_sounds("ll-arc-furnace", "electric-furnace")
copy_item_sounds("ll-low-grav-assembling-machine", "artillery-turret")
copy_item_sounds("ll-telescope", "storage-tank")
copy_item_sounds("ll-quantum-resonator", "lab")
copy_item_sounds("ll-quantum-module", "speed-module-3")
copy_item_sounds("ll-landing-pad", "cargo-landing-pad")
copy_item_sounds("ll-oxygen-diffuser", "steam-engine")
copy_item_sounds("ll-mass-driver", "laser-turret")
copy_item_sounds("ll-mass-driver-requester", "requester-chest")
copy_item_sounds("ll-mass-driver-capsule", "artillery-shell")
copy_item_sounds("ll-rocket-silo-interstellar", "rocket-silo", true)
copy_item_sounds("ll-silica", "sulfur")
copy_item_sounds("ll-silicon", "copper-cable")
copy_item_sounds("ll-alumina", "sulfur")
copy_item_sounds("ll-aluminium-plate", "iron-plate")
copy_item_sounds("ll-quantum-processor", "defender-capsule")
copy_item_sounds("ll-heat-shielding", "barrel")
copy_item_sounds("ll-packed-heat-shielding", "barrel")
copy_item_sounds("ll-packed-rocket-control-unit", "defender-capsule")
copy_item_sounds("ll-packed-low-density-structure", "low-density-structure")
copy_item_sounds("ll-blank-data-card", "iron-plate")
copy_item_sounds("ll-data-card", "speed-module-3")
copy_item_sounds("ll-quantum-data-card", "speed-module-3")
copy_item_sounds("ll-junk-data-card", "solid-fuel")
copy_item_sounds("ll-broken-data-card", "low-density-structure")
copy_item_sounds("ll-superposed-polariton", "poison-capsule")
copy_item_sounds("ll-up-polariton", "poison-capsule")
copy_item_sounds("ll-down-polariton", "poison-capsule")
copy_item_sounds("ll-left-polariton", "poison-capsule")
copy_item_sounds("ll-right-polariton", "poison-capsule")
copy_item_sounds("ll-moon-rock", "stone")
copy_item_sounds("ll-rich-moon-rock", "stone")
copy_item_sounds("ll-aluminium-ore", "stone")
copy_item_sounds("ll-ice", "poison-capsule")
copy_item_sounds("ll-astrocrystals", "poison-capsule")
copy_item_sounds("rocket-control-unit", "defender-capsule")
copy_item_sounds("ll-rocket-part-nauvis", "flying-robot-frame")
copy_item_sounds("ll-rocket-part-luna", "flying-robot-frame")
copy_item_sounds("ll-rocket-part-interstellar", "flying-robot-frame", true)
copy_item_sounds("ll-used-rocket-part", "flying-robot-frame")
copy_item_sounds("ll-space-science-pack", "automation-science-pack")
copy_item_sounds("ll-quantum-science-pack", "automation-science-pack")
